// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tamagochi.Data;

#nullable disable

namespace Tamagochi.Migrations
{
    [DbContext(typeof(TamagochiDbContext))]
    [Migration("20251004120000_IncreaseSavingsRatePrecision")]
    partial class IncreaseSavingsRatePrecision
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Tamagochi.Models.FinanceSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<decimal>("Expenses")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Income")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SavingsRate")
                        .HasColumnType("decimal(5,4)")
                        .HasPrecision(5, 4);

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FinanceSnapshots");
                });

            modelBuilder.Entity("Tamagochi.Models.Inventory", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Background")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Items")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("OwnedPets")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SelectedPetId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Inventories");
                });

            modelBuilder.Entity("Tamagochi.Models.Mission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductTag")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Repeatable")
                        .HasColumnType("bit");

                    b.Property<int>("RewardCoins")
                        .HasColumnType("int");

                    b.Property<string>("RewardPetId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RewardXp")
                        .HasColumnType("int");

                    b.Property<int>("Target")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Missions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "DEPOSIT_6M",
                            Description = "Узнай про вклад на 6–12 месяцев и кликни на продукт",
                            ProductTag = "deposit_6m",
                            Repeatable = false,
                            RewardCoins = 200,
                            RewardXp = 150,
                            Target = 1,
                            Title = "Открой вклад 6+ мес"
                        },
                        new
                        {
                            Id = 2,
                            Code = "SAVINGS_CUSHION",
                            Description = "Накопи 1× месячных расходов (демо-цель)",
                            ProductTag = "long_savings",
                            Repeatable = true,
                            RewardCoins = 300,
                            RewardXp = 200,
                            Target = 3,
                            Title = "Финансовая подушка"
                        },
                        new
                        {
                            Id = 3,
                            Code = "ANTIFRAUD_TUTORIAL",
                            Description = "Пройди мини-урок по антифроду",
                            ProductTag = "antifraud",
                            Repeatable = false,
                            RewardCoins = 200,
                            RewardPetId = "cat",
                            RewardXp = 120,
                            Target = 3,
                            Title = "Защита от мошенников"
                        },
                        new
                        {
                            Id = 4,
                            Code = "WEEKLY_BUDGET",
                            Description = "Составь план покупок и отметь три дня без импульсивных трат",
                            ProductTag = "weekly_budget",
                            Repeatable = true,
                            RewardCoins = 250,
                            RewardXp = 200,
                            Target = 3,
                            Title = "Неделя осознанных трат"
                        });
                });

            modelBuilder.Entity("Tamagochi.Models.MissionProgress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Counter")
                        .HasColumnType("int");

                    b.Property<int>("MissionId")
                        .HasColumnType("int");

                    b.Property<bool>("RewardClaimed")
                        .HasColumnType("bit");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MissionProgresses");
                });

            modelBuilder.Entity("Tamagochi.Models.PetProfile", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AvatarUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OwnedPetIds")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SelectedPetId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("PetProfiles");
                });

            modelBuilder.Entity("Tamagochi.Models.PetStatus", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Balance")
                        .HasColumnType("int");

                    b.Property<int>("Mood")
                        .HasColumnType("int");

                    b.Property<int>("Satiety")
                        .HasColumnType("int");

                    b.Property<int>("Xp")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.ToTable("PetStatuses");
                });

            modelBuilder.Entity("Tamagochi.Models.SavingsAccount", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateOnly?>("DepositMaturityDate")
                        .HasColumnType("date");

                    b.Property<decimal>("GoalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("HasDeposit")
                        .HasColumnType("bit");

                    b.Property<decimal>("MonthlyContribution")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("SavingsAccounts");
                });

            modelBuilder.Entity("Tamagochi.Models.ShopItem", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ShopItems");

                    b.HasData(
                        new
                        {
                            Id = "food_small",
                            Description = "+15 к сытости",
                            Enabled = true,
                            PayloadJson = "{\"satiety\":15}",
                            Price = 10,
                            Title = "Корм (мал.)",
                            Type = "food"
                        },
                        new
                        {
                            Id = "food_big",
                            Description = "+40 к сытости",
                            Enabled = true,
                            PayloadJson = "{\"satiety\":40,\"mood\":5}",
                            Price = 25,
                            Title = "Корм (бол.)",
                            Type = "food"
                        },
                        new
                        {
                            Id = "bg_sky",
                            Description = "Лёгкие облака",
                            Enabled = true,
                            PayloadJson = "{\"background\":\"sky\"}",
                            Price = 30,
                            Title = "Фон: Небо",
                            Type = "bg"
                        },
                        new
                        {
                            Id = "bg_room",
                            Description = "Уютное убежище",
                            Enabled = true,
                            PayloadJson = "{\"background\":\"room\"}",
                            Price = 30,
                            Title = "Фон: Комната",
                            Type = "bg"
                        },
                        new
                        {
                            Id = "ball",
                            Description = "Игра повышает настроение",
                            Enabled = true,
                            PayloadJson = "{\"item\":\"ball\"}",
                            Price = 20,
                            Title = "Мячик",
                            Type = "item"
                        },
                        new
                        {
                            Id = "pet_cat",
                            Description = "Компаньон с миссии",
                            Enabled = false,
                            PayloadJson = "{\"petId\":\"cat\"}",
                            Price = 500,
                            Title = "Открыть кота",
                            Type = "pet"
                        },
                        new
                        {
                            Id = "pet_dragon",
                            Description = "Эпический друг",
                            Enabled = false,
                            PayloadJson = "{\"petId\":\"dragon\"}",
                            Price = 1500,
                            Title = "Открыть дракона",
                            Type = "pet"
                        });
                });

            modelBuilder.Entity("Tamagochi.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Tamagochi.Models.Wallet", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Coins")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.ToTable("Wallets");
                });
#pragma warning restore 612, 618
        }
    }
}
