// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tamagochi.Data;

#nullable disable

namespace Tamagochi.Migrations
{
    [DbContext(typeof(TamagochiDbContext))]
    [Migration("20250921185020_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Tamagochi.Models.Tamagochi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Developer")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Tamagochis");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Developer = "Nikita",
                            Title = "Cat"
                        },
                        new
                        {
                            Id = 2,
                            Developer = "Nikita",
                            Title = "Dog"
                        },
                        new
                        {
                            Id = 3,
                            Developer = "Nikita",
                            Title = "Dragon"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
